[profile.default]
solc = "0.6.12"
block_timestamp = 1_680_220_800
bytecode_hash = "none"
evm_version = "paris"
fuzz = { runs = 1_000 }
optimizer_runs = 10_000

[fmt]
line_length = 120

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
